version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:1032@db:5432/collaborative-todo
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=1032
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1032
      POSTGRES_DB: collaborative-todo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
