version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:10321033@collaborative-todo-db.cbmgisugg4od.us-east-1.rds.amazonaws.com:5432/collaborative-todo
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=10321033
      - DATABASE_HOST=db  # Change to db for Docker networking
      - DATABASE_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 10321033
      POSTGRES_DB: collaborative-todo
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata: